# Generated by Django 2.2.9 on 2020-09-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200906_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
